In [ ]:
!Github URL = https://github.com/EomOrigin/OpensourceSW-Programming.git

/bin/bash: line 1: Github: command not found


#예제1

In [1]:
symbols = "$*&!@"
codes = []

for symbol in symbols:
    codes.append(ord(symbol))

print(codes)



[36, 42, 38, 33, 64]


#예제2

In [2]:
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]

print(codes)


[36, 42, 38, 33, 64]


#예제3


In [3]:
# 예제 3. 지능형 리스트 지역 변수와 주변 변수 구분 예제

x = '!!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)


!!~$$*&!@
[33, 33, 126, 36, 36, 42, 38, 33, 64]


#예제4

In [4]:
# 예제 4. 지능형 리스트로 만든 리스트
symbols = '!!~$$*&!@'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascii)



[33, 33, 126, 36, 36, 42, 38, 33, 64]


#예제5

In [5]:
# 예제 5. map()/filter()로 만든 리스트
symbols = '!!~$$*&!@'
beyond_ascii = list(filter(lambda c: c>64, map(ord, symbols)))

print(beyond_ascii, '\n')

print(f"Map function:\n>>> {map(ord, symbols)}")
print(f"List after map:\n>>> {list(map(ord, symbols))}")

[126] 

Map function:
>>> <map object at 0x7a018c634d90>
List after map:
>>> [33, 33, 126, 36, 36, 42, 38, 33, 64]


#예제6

In [6]:
# 예제 6. 지능형 리스트를 이용한 데카르트 곱
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
    for size in sizes:
        print((color, size))


[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


#예제7-1

In [7]:
# 예제 7. 제너레이터 표현식에서 튜플 초기화하기
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)


(33, 35, 94, 38, 38, 35)


#예제 7-2

In [8]:
# 예제 7. 제너레이터 표현식에서 배열 초기화하기
import array

ord_s = array.array('I', (ord(symbol) for symbol in symbols))

print(ord_s)



array('I', [33, 35, 94, 38, 38, 35])


#예제8

In [9]:
# 예제 8. 제너레이터 표현식에서의 데카르트 곱
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

for tshirt in ('{} {}'.format(c, s) for s in sizes for c in colors):
    print(tshirt)

black S
white S
black M
white M
black L
white L


#예제9

In [10]:
# 예제 9. 레코드로 사용된 튜플 1
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')


BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


#예제10

In [11]:
# 예제 10. 레코드로 사용된 튜플 2
for country, _ in traveler_ids:
    print(country)


USA
BRA
ESP


#예제11

In [12]:
# 예제 11. 튜플 병렬 할당
lax_coordinates = (33.9425, -118.408056)
latitude, longtitude = lax_coordinates
print(latitude)
print(longtitude)


33.9425
-118.408056


#예제12

In [13]:
# 예제 12. 튜플 병렬 할당 (swap)
a = 10; b = 20
b, a = a, b
print(a, b)



20 10


#예제 13

In [16]:
# 예제 13. 튜플 병렬 할당 (함수 인수 전달)
divmod(20, 8)


t = (20, 8)
divmod(*t)


quotient, remainder = divmod(*t)
quotient, remainder



(2, 4)

# 예제 14

In [17]:
# 예제 14. 파일시스템 경로에서 경로명과 파일명 추출
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename


'idrsa.pub'

#예제 15

In [18]:
# 예제 15. * 사용으로 병렬 할당 언패킹 1
a, b, *rest = range(5)
print(a, b, rest)


a, b, *rest = range(3)
print(a, b, rest)


a, b, *rest = range(2)
print(a, b, rest)



0 1 [2, 3, 4]
0 1 [2]
0 1 []


#예제 16

In [19]:
# 예제 16. * 사용으로 병렬 할당 언패킹 2
a, *body, c, d = range(5)
print(a, body, c, d)


*head, b, c, d = range(5)
print(head, b, c, d)



0 [1, 2] 3 4
[0, 1] 2 3 4


#예제 17

In [20]:
# 예제 17. longitude에 접근하기 위해 내포된 튜플 언패킹
metro_areas = [
    ("Tokyo", "JP", 36.933, (35, 139)),
    ("Delhi NCR", "IN", 21, (28, 77)),
    ("Mexico City", "MX", 20, (19, -99)),
    ("New York–Newark", "US", 20, (40, -74)),
    ("Sao Paulo", "BR", 19, (-23, -46)),
]

print("{:15} | {:^9} | {:^9}".format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'

for name, cc, pop, (lat, longi) in metro_areas:
    if longi <= 0:
        print(fmt.format(name, lat, longi))



                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York–Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


#예제 18


In [21]:
# 예제 18. 명명된 튜플형을 정의하고 사용하기
from collections import namedtuple
City = namedtuple('City', 'name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
print(tokyo)


print(tokyo.population)


print(tokyo.coordinates)


print(tokyo[1])



City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))
36.933
(35.689, 139.691)
JP


#예제 19

In [23]:
# 예제 19. 명명된 튜플의 속성과 메서드 (예제 18에 이어서)
print(City._fields)


LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))

delhi = City._make(delhi_data)
print(delhi._asdict())


for key, value in delhi._asdict().items():
    print(key + ':', value)


('name', 'country', 'population', 'coordinates')
{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lat=28.613, long=77.208)}
name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


#예제 20

In [22]:
# 예제 20. 슬라이싱 예제
l = [10, 20, 30, 40, 50, 60]
print(l[:2])
print(l[2:])


print(l[:3])


print(l[3:])



[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]


#예제 21

In [24]:
# 예제 21. 단순 텍스트 파일 청구서의 행 항목들
invoice = """
0....6...................25........33......40........
1909  Pimoroni          $17.50    3    $52.50
1489  6mm Tactile        $4.95    2     $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])


17.50    Pimoroni          $
$4.95    6mm Tactile        
 


#예제 22

In [25]:
# 예제 22. 가변 시퀀스 변형
l = list(range(10))
l[2:5] = [20, 30]

del l[5:7]

l[3::2] = [11, 22]


#예제 23

In [26]:
# 예제 23. 가변 시퀀스 변형 오류 예시
l[2:5] = 100


TypeError: can only assign an iterable

#예제 24

In [27]:
# 예제 24. 올바른 할당문
l[2:5] = [100]


#예제 25

In [28]:
# 예제 25. 시퀀스에 덧셈, 곱셈 수행
l = [1, 2, 3]
l * 5

5 * 'abcd'


'abcdabcdabcdabcdabcd'

#예제 26

In [29]:
# 예제 26. 길이가 3인 리스트 3개로 표현한 틱택토 보드
board = [['_'] * 3 for i in range(3)]
board[1][2] = 'X'


#예제 27

In [30]:
# 예제 27. 동일한 리스트에 대한 세 개의 참조를 가진 리스트 1
weird_board = [['_'] * 3] * 3
weird_board[1][2] = 'O'


#예제 28

In [31]:
# 예제 28. 동일한 리스트에 대한 세 개의 참조를 가진 리스트 2
row = ['_'] * 3
board = []
for i in range(3):
    board.append(row)

board[1][2] = 'X'


#예제 29

In [32]:
# 예제 29. [예제 26]의 지능형 리스트의 다른 표현
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)

board[2][0] = 'X'


#예제 30

In [33]:
# 예제 30. 가변 시퀀스의 복합 할당 연산자 곱 결과
l = [1, 2, 3]
id(l)
l *= 2
id(l)


134147087342784

#예제 31

In [34]:
# 예제 31. 불변 시퀀스의 복합 할당 연산자 곱 결과
t = (1, 2, 3)
id(t)
t *= 2
id(t)


134147068793216

#예제 32

In [35]:
# 예제 32. 퀴즈
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60]


(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

#예제 33

In [36]:
# 예제 33. 퀴즈 코드 수행 결과
print(t)


(1, 2, [30, 40, 50, 60])


#예제 34

In [37]:
# 예제 34. 리스트 정렬: sorted()
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

sorted(fruits, reverse=True)

sorted(fruits, key=len)


['grape', 'apple', 'banana', 'raspberry']

#예제 35

In [38]:
# 예제 35. 리스트 정렬: list.sort()
sorted(fruits, key=len, reverse=True)

fruits.sort()


#예제 36

In [39]:
# 예제 36. 커다란 실수 배열의 생성
from array import array
from random import random

floats = array('d', (random() for _ in range(10**7)))
floats[-1]


0.9419098220987572

#예제 37

In [40]:
# 예제 37. 커다란 실수 배열의 저장/로딩
with open('floats.bin', 'wb') as f:
    floats.tofile(f)

floats2 = array('d')
with open('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

floats2[-1]

floats == floats2


True

#예제 38

In [41]:
# 예제 38. 배열 항목 값의 바이트 중 하나 변경
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)

memv_oct = memv.cast('B')
memv_oct.tolist()

memv_oct[5] = 4
numbers


array('h', [-2, -1, 1024, 1, 2])

#예제 39

In [42]:
# 예제 39. numpy.ndarray에서 행과 열을 이용한 기본 연산
import numpy
a = numpy.arange(12)
a
type(a)


numpy.ndarray

#예제 40

In [43]:
# 예제 40. numpy.ndarray에서 행과 열을 이용한 기본 연산 2
a.shape = 3, 4
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#예제 41

In [44]:
# 예제 41. numpy.ndarray에서 행과 열을 이용한 기본 연산 3
a[2]

a[2, 1]

a[:, 1]


array([1, 5, 9])

#예제 42

In [45]:
# 예제 42. numpy.ndarray에서 행과 열을 이용한 기본 연산 4
a.transpose()


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#예제 43

In [46]:
# 예제 43. 덱(deque) 이용하기 1
from collections import deque
dq = deque(range(10), maxlen=10)
dq

dq.rotate(3)
dq

dq.rotate(-4)
dq


deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

#예제 44

In [47]:
# 예제 44. 덱(deque) 이용하기 2
dq.appendleft(-1)
dq

dq.extend([11, 22, 33])
dq

dq.extendleft([10, 20, 30, 40])
dq


deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8])